### PR TITLE
Fix UART

### PR DESCRIPTION
**Pull request by felmue**
Note: not sure if that is the correct fix, but it works for me.

### CODE REVIEW

**Comment by lbuque** [comment]
@felmue What problems did you encounter?

**Comment by felmue** [comment]
Hello @lbuque 

please see this [thread](https://community.m5stack.com/topic/6253/sorry-but-new-firmware-breaks-my-projects-again/3). The issue is that UART / GPS init block is broken for M5Dial. (And is still broken in UIFlow2.0.4)

I created a ProjectZone [example](https://uiflow2.m5stack.com/?pkey=b6911e9aaca84c4fbd1f7e9881c31fbc): _M5Dial_GPS_Unit_UIFlow2.0.2_ which shows the issue.

The error I am getting is: _OSError: (-261, 'ESP_ERR_NOT_FOUND')_

Thanks
Felix

**Comment by lbuque** [comment]
@felmue I ran M5Dial_GPS_Unit_UIFlow2.0.2 using firmware 2.0.4 and it seemed to run normally. What did I miss?

**Comment by felmue** [comment]
Hello @lbuque 

thank you for checking. Hmm, strange. And you are running UIFlow2.0.4 firmware on your M5Dial installed with M5Burner?

Thanks
Felix

**Comment by lbuque** [comment]
@felmue The startup ui uses port a. When running main.py, it is not initialized, which will cause uart initialization to fail.

This is my solution:

```diff
diff --git a/m5stack/modules/startup/dial/framework.py b/m5stack/modules/startup/dial/framework.py
index d1327d5..8a07ea4 100644
--- a/m5stack/modules/startup/dial/framework.py
+++ b/m5stack/modules/startup/dial/framework.py
@@ -49,12 +49,12 @@ class Framework:
         app.start()
 
     async def run(self):
-        self.i2c0 = I2C(0, scl=Pin(15), sda=Pin(13), freq=100000)
+        # self.i2c0 = I2C(0, scl=Pin(15), sda=Pin(13), freq=100000)
         self._kb_status = False
-        if 0x5F in self.i2c0.scan():
-            self._kb = CardKBUnit(self.i2c0)
-            self._event = KeyEvent()
-            self._kb_status = True
+        # if 0x5F in self.i2c0.scan():
+        #     self._kb = CardKBUnit(self.i2c0)
+        #     self._event = KeyEvent()
+        #     self._kb_status = True
         rotary = Rotary()
 
         self._bar and self._bar.start()
```

**Comment by lbuque** [comment]
> @felmue The startup ui uses port a. When running main.py, it is not initialized, which will cause uart initialization to fail.
> 
> This is my solution:
> 
> ```diff
> diff --git a/m5stack/modules/startup/dial/framework.py b/m5stack/modules/startup/dial/framework.py
> index d1327d5..8a07ea4 100644
> --- a/m5stack/modules/startup/dial/framework.py
> +++ b/m5stack/modules/startup/dial/framework.py
> @@ -49,12 +49,12 @@ class Framework:
>          app.start()
>  
>      async def run(self):
> -        self.i2c0 = I2C(0, scl=Pin(15), sda=Pin(13), freq=100000)
> +        # self.i2c0 = I2C(0, scl=Pin(15), sda=Pin(13), freq=100000)
>          self._kb_status = False
> -        if 0x5F in self.i2c0.scan():
> -            self._kb = CardKBUnit(self.i2c0)
> -            self._event = KeyEvent()
> -            self._kb_status = True
> +        # if 0x5F in self.i2c0.scan():
> +        #     self._kb = CardKBUnit(self.i2c0)
> +        #     self._event = KeyEvent()
> +        #     self._kb_status = True
>          rotary = Rotary()
>  
>          self._bar and self._bar.start()
> ```
> 
> I don't recommend using UART on PORTA.

This method does not solve the problem 100%. It still has a high probability of abnormalities.

**Comment by felmue** [comment]
Hello @lbuque 

thank you for looking into this.

BTW: I tried port B (instead of port A), but I get the same error as reported before.

Thanks
Felix

**Comment by lbuque** [comment]
@felmue I updated Dial's firmware on M5Burner, please verify.

**Comment by felmue** [comment]
Hello @lbuque 

I can confirm that M5Dial _v2.0.4--hotfix_ firmware resolves the issue. I tested port A and B and both work fine now.

Thank you very much.

Thanks
Felix

**Comment by jasperlatour** [comment]
im trying to use the m5stack gps unit, but nothing seems to work , and yes i tried the hotfix

**Comment by lbuque** [comment]
> im trying to use the m5stack gps unit, but nothing seems to work , and yes i tried the hotfix

I hope you can report more information to me.

**Comment by jasperlatour** [comment]
when i try the example for using the gps unit with the m5dial, i still get the same error as described in this pull request. I also tried the hotfix as described, but i still get the same error

**Comment by jasperlatour** [comment]
i maanged to get the program running now on the m5 dial, thanks for that.

But now i cant get the m5dial to print the data from the gps, it prints the labels, but all the data received from the gps are:
lat 0N
long: 0E
alt: 0
#: 0

can you help me fix this

**Comment by lbuque** [comment]
@jasperlatour Did you move the GPS Unit outdoors?

PS: You should open a new issue instead of asking on a closed PR (which has nothing to do with the problem you are facing). Your approach will make it easy for us to ignore this problem.

**Pull request closed without merging**
